apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations: 
        eks.tke.cloud.tencent.com/eip-attributes: ""  #需求EIP，配置均为默认
        eks.tke.cloud.tencent.com/spot-pod: "true"
    spec:
      containers:
      - name: busybox
        image: rancher/kubectl
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
        # command: ["printenv"]
        # args: ["HOSTNAME", "KUBERNETES_PORT"]
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi